name: NPM Package
on:
  release:
    types:
      - created
      - edited
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: ${{ github.repository_owner }}
      - name: Create a package called @${{ github.repository }}
        run: npm init --scope ${{ github.repository_owner }} -y
      - name: Install dependencies
        run: npm ci
      - name: Build the package
        run: npm pack
      - name: Publish the package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
